PYPI_NAMES = {
    "google.cloud.pubsub_v1": "google-cloud-pubsub",
    "google.cloud.logging": "google-cloud-logging",
    "google.cloud.core": "google-cloud-core",
    "google.cloud.storage": "google-cloud-storage",
    "gcsfs": "gcsfs",
    "google.cloud.bigquery": "google-cloud-bigquery",
    "google.cloud.firestore": "google-cloud-firestore",
    "pyarrow": "pyarrow",
    "pandas_gbq": "pandas-gbq",
    "pandas": "pandas",
    "google.cloud.functions_v1": "google-cloud-functions",
    "google.auth": "google-auth",
    "google.oauth2": "google-auth-oauthlib",
}
