name: Build and publish gcp-pal to PyPI
on:
  push:
    branches:
    - main

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate GCP using workload identity
      uses: google-github-actions/auth@v0.4.0
      with:
        workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install poetry
      run: python3 -m pip install poetry --user

    - name: Install dependencies
      run: python3 -m poetry install

    - name: Run tests
      run: ./runtests.sh

    - name: Build distribution
      run: python3 -m poetry build

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
