name: Build and publish gcp-pal to PyPI and GitHub

on:
  push:
    branches:
    - main

jobs:
  pypi-and-github:
    permissions:
      contents: 'write'
      id-token: 'write'

    name: Publish to PyPI and GitHub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Authenticate GCP using workload identity
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install poetry
      run: python3 -m pip install poetry --user

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create false --local
        poetry install --all-extras

    - name: Run tests
      run: |
        ./runtests.sh | tee output.txt
        if grep -q "= FAILURES =" output.txt; then
          echo "Tests failed"
          exit 1
        fi

    - name: Build distribution
      run: python3 -m poetry build

    - name: Get version from poetry
      id: get_version
      run: echo "VERSION=$(poetry version -s)" >> $GITHUB_ENV

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{ env.VERSION }}"
        release_name: "Release ${{ env.VERSION }}"
        body: "New release ${{ env.VERSION }}"
        draft: false
        prerelease: false
